# -*- coding: utf-8 -*-
"""Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R2HTrNcXDRJtOYLEDSTNhHPvG0W8wdst
"""

import streamlit as st
import pandas as pd
import numpy as np

# Set page title
st.title('Simple Dashboard with Streamlit')

# Generate sample data
np.random.seed(42)
data = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', periods=100, freq='D'),
    'Value': np.random.randn(100).cumsum()
})

# Sidebar filters
st.sidebar.header('Filters')
date_filter = st.sidebar.date_input('Select a date range', [data['Date'].min(), data['Date'].max()])
filtered_data = data[(data['Date'] >= date_filter[0]) & (data['Date'] <= date_filter[1])]

# Main panel
st.subheader('Line Chart')
st.line_chart(filtered_data.set_index('Date'))

st.subheader('Bar Chart')
st.bar_chart(filtered_data.set_index('Date'))

st.subheader('Statistics')
st.write(filtered_data.describe())

# Run the Streamlit app
if __name__ == '__main__':
    st.write('Run this script with: `streamlit run <script_name.py>`')